begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select set_config('test.eid', (select id::text from app_private.events where slug='duindorp-halloween-2026'), true);
insert into app_private.editorial_media(id,event_id,alt,width,height,byte_size,created_by)
values ('b8400000-0000-0000-0000-000000000001',current_setting('test.eid')::uuid,'Een poort',1600,900,1000,'f0000000-0000-0000-0000-000000000001');
select set_config('test.content', '{"internalName":"Testmail behouden","subject":"De poorten gaan open","preheader":"Nieuws voor de wijk","eyebrow":"NACHTPOST","article":{"title":"De nacht komt dichterbij","intro":"Een veilige introductie","heroId":"b8400000-0000-0000-0000-000000000001","heroAlt":"Een poort","heroCaption":"","author":"Organisatie","categoryId":null,"body":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Samen maken we de nacht."}]}]},"cta":null},"newsVersionIds":[],"closing":"Tot tussen de poorten","senderName":"Duindorpse Poorten"}',true);
update app_private.participant_preferences set optional_updates_consent=false where event_id=current_setting('test.eid')::uuid;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"a0000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
select api.editorial_preferences_set('duindorp-halloween-2026',true,false,false);
select set_config('request.jwt.claims','{"sub":"f0000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
select set_config('test.saved',api.admin_newsletter_save('duindorp-halloween-2026',null,0,current_setting('test.content')::jsonb,'{"roles":["parents"]}',true)::text,true);
select set_config('test.id',current_setting('test.saved')::jsonb->>'id',true);
select set_config('test.version',current_setting('test.saved')::jsonb->>'versionId',true);
reset role;
create function pg_temp.campaign() returns jsonb language sql as $$
  select item from jsonb_array_elements(api.admin_editorial_snapshot('duindorp-halloween-2026')->'campaigns') item
  where item->>'id'=current_setting('test.id');
$$;
select ok(not has_function_privilege('anon','app_private.newsletter_test_result(uuid)','execute'),'test evidence is not public');
select ok(not has_function_privilege('authenticated','app_private.newsletter_test_result(uuid)','execute'),'clients cannot look up private test evidence');
set local role authenticated;
select is(pg_temp.campaign()->>'testAccepted','false','untested campaign is blocked');
select throws_ok($$select api.admin_newsletter_schedule(current_setting('test.version')::uuid,now(),1)$$,'P0001','TEST_MAIL_REQUIRED','server requires a real test result');
select set_config('test.mail',api.admin_newsletter_test(current_setting('test.version')::uuid,gen_random_uuid())::text,true);
select is(pg_temp.campaign()->>'testStatus','pending','snapshot explains pending test');
select is(pg_temp.campaign()->>'testAccepted','false','queued mail cannot unlock sending');
reset role;
update app_private.email_outbox set status='accepted',provider_id='local-fixture' where id=current_setting('test.mail')::uuid;
set local role authenticated;
select is(pg_temp.campaign()->>'testAccepted','true','provider acceptance unlocks review');
select is(api.admin_newsletter_save('duindorp-halloween-2026',current_setting('test.id')::uuid,1,current_setting('test.content')::jsonb,'{"roles":["parents"]}',true),current_setting('test.saved')::jsonb,'unchanged save retains exact version and revision');
reset role;
select is((select count(*)::int from app_private.audit_events where resource_id=current_setting('test.id')::uuid and action='newsletter.draft_saved'),1,'unchanged save does not create a misleading edit audit');
update app_private.email_outbox set status='delivered' where id=current_setting('test.mail')::uuid;
-- Reproduce redundant versions created by the old save RPC, without changing mail.
insert into app_private.content_versions(event_id,page_key,structured_content,version,created_by,content_kind,campaign_id)
select event_id,page_key,structured_content,2,created_by,content_kind,campaign_id from app_private.content_versions where id=current_setting('test.version')::uuid;
update app_private.newsletter_campaigns set revision=2 where id=current_setting('test.id')::uuid;
select set_config('test.version2',(select id::text from app_private.content_versions where campaign_id=current_setting('test.id')::uuid and version=2),true);
set local role authenticated;
select is(pg_temp.campaign()->>'testAccepted','true','received test remains valid after an old redundant save');
select is(pg_temp.campaign()->>'testStatus','delivered','received status is retained');
select is(pg_temp.campaign()->>'testedVersion','1','snapshot identifies the equivalent tested version');
select throws_ok($$select api.admin_newsletter_save('duindorp-halloween-2026',current_setting('test.id')::uuid,1,current_setting('test.content')::jsonb,'{"roles":["parents"]}',true)$$,'40001','STALE_VERSION','even unchanged saves preserve optimistic locking');
select set_config('test.other',api.admin_newsletter_save('duindorp-halloween-2026',null,0,current_setting('test.content')::jsonb,'{"roles":["parents"]}',true)::text,true);
select throws_ok($$select api.admin_newsletter_schedule((current_setting('test.other')::jsonb->>'versionId')::uuid,now(),1)$$,'P0001','TEST_MAIL_REQUIRED','identical content in another campaign cannot borrow a test');
select set_config('test.changed',api.admin_newsletter_save('duindorp-halloween-2026',current_setting('test.id')::uuid,2,current_setting('test.content')::jsonb || '{"subject":"Andere inhoud"}','{"roles":["parents"]}',true)::text,true);
select is(pg_temp.campaign()->>'testAccepted','false','real content change invalidates the earlier test');
select throws_ok($$select api.admin_newsletter_schedule((current_setting('test.changed')::jsonb->>'versionId')::uuid,now(),1)$$,'P0001','TEST_MAIL_REQUIRED','changed mail cannot be sent using old proof');
select set_config('test.changed_mail',api.admin_newsletter_test((current_setting('test.changed')::jsonb->>'versionId')::uuid,gen_random_uuid())::text,true);
reset role;
update app_private.email_outbox set status='failed' where id=current_setting('test.changed_mail')::uuid;
set local role authenticated;
select is(pg_temp.campaign()->>'testStatus','failed','failed test has an explicit status');
select is(pg_temp.campaign()->>'testAccepted','false','failed test cannot unlock sending');
reset role;
update app_private.email_outbox set status='unknown' where id=current_setting('test.changed_mail')::uuid;
set local role authenticated;
select is(pg_temp.campaign()->>'testAccepted','false','uncertain delivery cannot unlock sending');
select set_config('test.restored',api.admin_newsletter_save('duindorp-halloween-2026',current_setting('test.id')::uuid,3,current_setting('test.content')::jsonb,'{"roles":["parents"]}',true)::text,true);
select is(pg_temp.campaign()->>'testAccepted','true','restoring exactly the tested mail restores its proof');
select throws_ok($$select api.admin_newsletter_schedule((current_setting('test.restored')::jsonb->>'versionId')::uuid,now(),99)$$,'40001','AUDIENCE_CHANGED','recipient count must still be reviewed');
select lives_ok($$select api.admin_newsletter_schedule((current_setting('test.restored')::jsonb->>'versionId')::uuid,now(),1)$$,'received equivalent test permits scheduling');
select lives_ok($$select api.admin_newsletter_schedule((current_setting('test.restored')::jsonb->>'versionId')::uuid,now(),1)$$,'schedule retry remains idempotent');
select is(pg_temp.campaign()->>'testAccepted','true','freezing the derived news cards retains test evidence');
reset role;
select is((select count(*)::int from app_private.newsletter_recipients where campaign_id=current_setting('test.id')::uuid),1,'exactly one recipient is frozen');
select is((select count(*)::int from app_private.audit_events where resource_id=current_setting('test.id')::uuid and action='newsletter.scheduled'),1,'exactly one schedule audit');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"a0000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
select throws_ok($$select api.admin_editorial_snapshot('duindorp-halloween-2026')$$,'42501','NOT_AUTHORIZED','ordinary parent cannot inspect campaigns');
select throws_ok($$select api.admin_newsletter_schedule((current_setting('test.restored')::jsonb->>'versionId')::uuid,now(),1)$$,'42501','NOT_AUTHORIZED','ordinary parent cannot schedule even tested mail');
select * from finish();
rollback;
