export type FaqCategory = { id: string; title: string; intro: string; questions: { id: string; question: string; answer: string; featured?: boolean }[] };
export const faqCategories: FaqCategory[] = [
  { id: "meedoen", title: "Meedoen aan de avond", intro: "Van inschrijven tot samen de wijk in.", questions: [
    { id: "hoe-werkt-het", featured: true, question: "Hoe werkt de Halloween-tocht?", answer: "Schrijf je kinderen in via Meelopen. Je geeft aan wanneer jullie graag starten en met wie jullie willen samenlopen. De organisatie maakt de wandelgroepen en bevestigt jullie startafspraak. Op 31 oktober wandelen de kinderen samen met een verantwoordelijke volwassene langs de poorten in Duindorp. De groepsleider ziet onderweg steeds de volgende bestemming in de app. Jullie sluiten de tocht af bij de laatste poort." },
    { id: "leeftijd", featured: true, question: "Voor welke leeftijd is de tocht?", answer: "De tocht is voor kinderen die samen met een volwassene op pad gaan. De werelden verschillen in spanning: er zijn rustige, magische poorten en poorten met acteurs en schrikmomenten. Bekijk de uitleg bij de werelden en kies wat bij je kind past. Je mag een poort altijd overslaan. Een kind hoeft nooit alleen verder en hoeft niets te doen wat niet prettig voelt." },
    { id: "bijdrage", featured: true, question: "Wat kost deelname?", answer: "De bijdrage is €2,50 per kind. Daarmee helpen we deelnemende huizen waar nodig aan snoep. Volwassen begeleiders lopen gratis mee. Na inschrijving vind je de betaalinformatie per kind in Mijn inschrijving. Gebruik het betaalverzoek dat daar voor jullie klaarstaat. Een betaling melden is nog geen bevestiging: de organisatie controleert de ontvangst. De betaling moet vóór 30 oktober bevestigd zijn." },
    { id: "tijden", question: "Hoe laat begint en eindigt de avond?", answer: "De Halloween-avond is op zaterdag 31 oktober 2026, tussen 17:00 en 21:00 uur. Groepen vertrekken op verschillende momenten. Volg de persoonlijke starttijd en het startpunt die de organisatie voor jullie publiceert. Jullie eigen eindtijd hangt samen met de gekozen voorkeuren en de tocht. Ga niet op eigen initiatief eerder naar een poort." },
    { id: "aantal-poorten", question: "Hoeveel poorten bezoeken we?", answer: "Dat verschilt per groep. De groepsleider kan aangeven hoeveel gewone poorten jullie maximaal willen bezoeken, of kiezen om door te lopen zolang er tijd is. De beschikbare poorten, starttijd en het moment waarop jullie willen afronden bepalen wat haalbaar is. Het gekozen aantal is een maximum, geen belofte. De laatste poort volgt aan het einde van jullie tocht." },
    { id: "meenemen", question: "Wat nemen we mee?", answer: "Warme kleding waarin je prettig kunt lopen, een lampje of reflectie, een snoeptas en een opgeladen telefoon voor de volwassene. Bekijk voor vertrek jullie startafspraak en spreek af dat de kinderen bij de groep blijven. In het Poortenboek kan ieder kind een eigen voorbereidingslijst afvinken. De groepsleider controleert bij vertrek nog apart wie er aanwezig is." },
  ]},
  { id: "inschrijving", title: "Inschrijving, betalen en samenlopen", intro: "Jullie gegevens en wensen op één plek.", questions: [
    { id: "samenlopen", featured: true, question: "Kunnen we samenlopen met vrienden?", answer: "Ja. Iedere inschrijving krijgt een eigen samenloopcode van vier tekens. Vul de code van je vrienden in bij het inschrijven of later bij Samenloop in Mijn inschrijving. De organisatie beoordeelt of jullie samen kunnen lopen, onder meer op groepsgrootte. Je ziet daar of het verzoek nog wacht, is goedgekeurd of is afgewezen. Pas na goedkeuring horen jullie bij dezelfde samenloop. De kinderen van die bevestigde samenloop zien elkaar als reisgenootjes in het Poortenboek." },
    { id: "samenloop-wijzigen", question: "Kan ik een samenloopverzoek aanpassen of annuleren?", answer: "Open Mijn inschrijving en kijk bij Samenloop. Zolang een verzoek nog openstaat, kun je het intrekken en een andere viertekencode insturen. Is de samenloop al bevestigd of staat de groepsindeling vast, vraag de organisatie dan via Hulp om de wijziging. Het verbreken van een samenloop annuleert de inschrijving van je kind niet." },
    { id: "voorkeuren", question: "Kan ik een gewenste start- en eindtijd opgeven?", answer: "Ja. Bij je inschrijving geef je een gewenste starttijd en een moment op waarna je geen nieuwe gewone poort meer wilt bezoeken. Zolang de indeling open is, kun je die voorkeuren aanpassen in Mijn inschrijving. De organisatie stemt de wensen van de hele groep af en bevestigt de startafspraak. De wandeling naar en het bezoek aan de laatste poort volgen na jullie gewone bezoeken." },
    { id: "gegevens-wijzigen", question: "Waar wijzig ik een inschrijving of meld ik een kind af?", answer: "Log in met het e-mailadres waarmee je de kinderen hebt ingeschreven en open Mijn inschrijving. Daar vind je de kinderen, contactgegevens, betaalinformatie en beschikbare wijzigingsacties. Na de wijzigingsdeadline lopen sommige aanpassingen via de organisatie. Gebruik dan Hulp van de organisatie. Controleer bij een afmelding ook de betaalstatus; een afmelding betekent niet automatisch dat geld is teruggestort." },
    { id: "betaling", question: "Ik heb betaald, maar zie nog geen bevestiging. Wat nu?", answer: "Open het juiste betaalverzoek in Mijn inschrijving en meld daar dat je hebt betaald. De organisatie controleert de ontvangen betaling. Tot die controle is afgerond kan er nog Wacht op bevestiging staan. Betaal niet nogmaals alleen omdat de status niet direct verandert. Stuur bij twijfel een privébericht aan de organisatie en vermeld je inschrijfnummer." },
    { id: "startafspraak", question: "Wanneer ontvangen we de starttijd?", answer: "Zodra de organisatie de groepsindeling publiceert, verschijnen de starttijd, het startpunt en de verzamelinstructie in jullie persoonlijke omgeving. Je ontvangt daarover ook bericht. Een tijdsvoorkeur bij inschrijving is nog geen bevestigde afspraak. Bekijk de actuele informatie opnieuw voor jullie vertrekken." },
  ]},
  { id: "poortenboek", title: "Het Poortenboek voor kinderen", intro: "Een eigen avontuur, ook op de telefoon van een ouder.", questions: [
    { id: "wat-is-poortenboek", featured: true, question: "Wat is het Poortenboek en heeft mijn kind een eigen telefoon nodig?", answer: "Het Poortenboek is het persoonlijke Halloweenboek van ieder ingeschreven kind. Daarin bereiden kinderen zich voor, kiezen ze met hun reisgenootjes een teamnaam en vaandel en maken ze een eigen verschijning met lantaarn. Tijdens de tocht verzamelen ze poortzegels en gaat hun verhaal verder. Een eigen telefoon is niet nodig: een ouder kan in Mijn inschrijving bij ieder kind op Open Poortenboek drukken. Op een ander apparaat kan het kind de persoonlijke code van zes tekens gebruiken." },
    { id: "kindcode", question: "Waar vind ik de code van mijn kind?", answer: "Log als ouder in met het e-mailadres van de inschrijving. In Mijn inschrijving staat bij ieder kind het onderdeel Poortenboek. Daar kun je de code bekijken en kopiëren. De code heeft zes tekens en is iets anders dan de samenloopcode van vier tekens. Deel de kindcode alleen met mensen die het boek van dat kind mogen openen." },
    { id: "code-vernieuwen", question: "Wat als mijn kind de code kwijt is of iemand anders de code kent?", answer: "Je kunt de bestaande code als ouder opnieuw bekijken. Wil je de toegang opnieuw instellen, kies dan Code vernieuwen en bevestig dit. De oude code werkt daarna niet meer en alle open kindersessies worden afgesloten. De voortgang van het kind blijft bewaard. Met Alle kindersessies afsluiten kun je open boeken sluiten zonder de code te veranderen." },
    { id: "reisgenootjes", question: "Wie ziet mijn kind bij Jouw reisgenootjes?", answer: "Alleen kinderen uit dezelfde inschrijving en uit een door de organisatie goedgekeurde samenloop. Andere kinderen die toevallig in dezelfde grote wandelgroep zijn ingedeeld, verschijnen hier niet automatisch. Reisgenootjes zien elkaars voornaam, een decoratief medaillon en algemene voorbereiding. Ze zien geen achternaam, leeftijd, adres of contactgegevens. Het Poortenboek heeft geen kinderchat en geen foto-upload." },
    { id: "teamnaam", question: "Hoe kiezen kinderen een teamnaam en vaandel?", answer: "Op Team kiest ieder kind maximaal drie favoriete namen. Iedere gekozen naam telt even zwaar. Zodra iedereen heeft gekozen, of de stemtijd voorbij is, wordt de teamnaam bekend. Bij een gelijkspel kiest de Magische Poort. Het vaandel stellen de reisgenootjes samen door favoriete onderdelen te kiezen. Een kind dat alleen een team vormt kan direct een naam kiezen. De naam van dit kleine kindteam staat los van de naam van de grotere wandelgroep." },
    { id: "zegels", question: "Hoe verdient een kind poortzegels?", answer: "Na een afgerond bezoek van jullie groep verschijnt de bijbehorende zegel in het Poortenboek. Je hoeft daarvoor op de kindertelefoon niets te scannen. De groepsleider regelt het echte bezoek in de groepsomgeving. De oefenpoort helpt kinderen wennen aan de beleving, maar telt niet als echt poortbezoek. Aan het eind kunnen kinderen hun terugblik en bewaarkaart bekijken." },
    { id: "kind-uitloggen", question: "Waarom vraagt het Poortenboek soms opnieuw om de code?", answer: "Een geopend Poortenboek blijft maximaal twaalf uur ingelogd. Daarna open je het opnieuw met de code of via het ouderaccount. Dat gebeurt ook wanneer de ouder de code vernieuwt of de kindersessies afsluit. De keuzes, voorbereiding en verdiende zegels blijven bewaard. Kies bij Ik voor Poortenboek sluiten voordat je het boek van een ander kind opent." },
  ]},
  { id: "poortkamer", title: "De Poortkamer voor huizen en teams", intro: "Bereid samen jullie poort voor en volg de avond.", questions: [
    { id: "plek-aanmelden", question: "Kan een huis, portiek of bedrijf ook meedoen?", answer: "Ja. Meld je plek aan via Plek aanmelden. Vul de contactgegevens in, bevestig je e-mailadres en werk de beschrijving, het thema, de openingstijden en praktische informatie uit. De organisatie beoordeelt de aanmelding. Na goedkeuring krijg je toegang tot de Poortkamer. Daar vind je de voorbereiding, het poortteam, de verwachte groepen en berichten." },
    { id: "team-uitnodigen", question: "Hoe nodig ik mensen uit voor mijn poortteam?", answer: "Als hoofdpoortwachter open je Team in de Poortkamer en kies je Deel een sleutel. Vul de naam, het e-mailadres en de rol van je teamlid in. Het teamlid krijgt een persoonlijke uitnodiging en bevestigt de toegang. Je kunt daarna de rol, het toegangsniveau en de chatmoderatie aanpassen. Ook kun je toegang tijdelijk uitzetten, weer activeren of intrekken." },
    { id: "poort-chat", question: "Welke chats zijn er in de Poortkamer?", answer: "Achter de Poort is voor je eigen team. De Praatkamer is de gezamenlijke ontmoetingsplek voor goedgekeurde poortteams en de organisatie, met kanalen voor tips en overleg. Nieuwe berichten verschijnen automatisch. Je kunt reageren, iemand vermelden of meldingen van een kanaal dempen. Houd gesprekken vriendelijk en deel geen persoonlijke gegevens van kinderen." },
    { id: "moderatie", question: "Wie beheert de chats?", answer: "De hoofdpoortwachter beheert de eigen teamchat en kan teamleden als moderator aanwijzen. Moderators kunnen berichten vastzetten of verbergen. De organisatie modereert de gezamenlijke Praatkamer en behandelt meldingen over berichten. Via de drie puntjes bij een bericht kun je een probleem melden. De organisatie kan iemand in de Praatkamer tijdelijk een spreekpauze geven." },
    { id: "updates", question: "Waar staan berichten van de organisatie?", answer: "Op de Nachtwacht, het beginscherm van jullie Poortkamer, staat Kort bijgepraat met de laatste aanwijzingen. Onder Berichten vind je alle mededelingen in De Omroeper. Daaronder op de Nachtwacht staat ook het nieuws voor de deelnemende poorten. Voor een persoonlijke vraag gebruik je Hulp van de organisatie. Bel bij direct gevaar 112." },
    { id: "poort-status", question: "Wanneer gebruik ik Open, Pauze of Gestopt?", answer: "Zet jullie poort op Open wanneer jullie klaarstaan om groepen te ontvangen. Gebruik Pauze wanneer jullie even geen nieuwe groep kunnen ontvangen. Je kunt een duur kiezen; de poort gaat daarna weer open. Kies Gestopt wanneer jullie stoppen en geef een reden. Groepen kunnen dan anders worden geleid. Rond het bezoek van een aanwezige groep rustig af en neem bij twijfel contact op met de organisatie." },
    { id: "presentatie", question: "Hoe verandert de voorstelling van onze poort in het Poortenboek?", answer: "Bij Meer in de Poortkamer kun je de naam, beschrijving, het korte verhaal, beeld, symbool en praktische kenmerken van jullie poort voorbereiden. Stuur de presentatie daarna ter beoordeling naar de organisatie. Na goedkeuring gebruiken nieuwe bezoeken de nieuwe presentatie. Reeds verdiende zegels bewaren het verhaal dat bij dat bezoek hoorde." },
    { id: "oefenen-poort", question: "Kunnen we de Poortkamer vooraf oefenen?", answer: "Ja. Bij Meer vind je de oefenstand. Daarmee speel je situaties na, zoals een naderende groep, drukte, pauze en een melding aan de organisatie. Alles in deze oefenstand is fictief. Er worden geen echte deelnemers verplaatst of echte berichten verstuurd. Zo kan je team rustig wennen aan de bediening." },
  ]},
  { id: "app", title: "De app, inloggen en meldingen", intro: "Handig op iPhone, Android en in je browser.", questions: [
    { id: "inloggen", question: "Hoe log ik als ouder of poortwachter in?", answer: "Gebruik je e-mailadres op de inlogpagina. Je ontvangt een tijdelijke inlogcode per e-mail. Neem die over in hetzelfde inlogscherm. Je hebt geen wachtwoord nodig. Gebruik het adres waarmee je hebt ingeschreven of waarvoor je een uitnodiging hebt ontvangen. De kindcode voor het Poortenboek werkt alleen op de Poortenboek-inlogpagina." },
    { id: "installeren", question: "Kan ik de app op mijn beginscherm zetten?", answer: "Ja, je kunt de website als app gebruiken. Op iPhone open je de site in Safari, tik je op Deel en kies je Zet op beginscherm. In Chrome of Samsung Internet op Android staat Installeren of Toevoegen aan startscherm in het browsermenu. Je kunt ook de installatiehulp in je persoonlijke omgeving gebruiken. Installeren is niet verplicht: de website blijft in de browser werken." },
    { id: "meldingen-aan", question: "Hoe zet ik meldingen aan?", answer: "Open de meldingsinstellingen in je persoonlijke omgeving of Poortkamer en geef toestemming op dit apparaat. Op iPhone werken webpushmeldingen in de geïnstalleerde app vanaf het beginscherm. Nieuwsbrieven via Nachtpost en pushmeldingen hebben ieder hun eigen voorkeuren. Je kunt ze later weer uitzetten. Belangrijke start- en bezoekinformatie blijft ook in je omgeving staan." },
    { id: "offline", question: "Wat als onze telefoon tijdelijk geen verbinding heeft?", answer: "Blijf met je groep bij elkaar op een veilige plek. De routeomgeving laat de laatst bevestigde aanwijzing en de bijwerktijd zien; een nieuwe bestemming vraagt verbinding. Chatberichten kun je pas versturen zodra je weer online bent. Het Poortenboek toont offline een neutraal scherm en haalt na herstel het juiste boek opnieuw op. Lukt herstellen niet, neem dan contact op met de organisatie." },
    { id: "gedeeld-apparaat", question: "Kunnen meerdere kinderen dezelfde telefoon gebruiken?", answer: "Ja. De ouder kan vanuit Mijn inschrijving het boek van een kind openen. Ga terug naar het ouderaccount om een ander kind te kiezen. In het boek ziet een kind het eigen avontuur en de reisgenootjes. Je ouderaccount blijft apart aangemeld op jouw toestel. Sluit het boek via Ik wanneer je wisselt. Log ook uit als ouder als je de telefoon zonder oudertoegang wilt meegeven." },
    { id: "beweging", question: "Kan ik de animaties of het geluid uitzetten?", answer: "Ja. Gebruik de bewegingsknop of de instelling bij Ik in het Poortenboek. Als je telefoon minder beweging vraagt, volgt de app die voorkeur. Geluid staat standaard uit en kun je zelf inschakelen. Alle uitleg en acties blijven ook zonder beweging en geluid beschikbaar." },
  ]},
  { id: "veilig-op-pad", title: "Samen op pad en hulp", intro: "Een fijne avond begint bij duidelijke afspraken.", questions: [
    { id: "te-spannend", question: "Kan mijn kind een poort overslaan?", answer: "Altijd. Overleg met de groepsleider als een poort te spannend, te donker of niet prettig is. De groep kan een poort overslaan. Een verantwoordelijke volwassene blijft bij de kinderen; stuur een kind nooit alleen verder. Bekijk vooraf de waarschuwingen voor bijvoorbeeld rook, lichtflitsen, geluid of acteurs." },
    { id: "route-kaart", question: "Staan alle huisadressen op de openbare kaart?", answer: "De openbare kaart laat Duindorp en de sfeer van de werelden zien. Deelnemende huisadressen zijn niet publiek zichtbaar. Tijdens de tocht krijgt de groepsleider de actuele bestemming te zien. Meekijkers zien beperkte voortgang, zonder toekomstige adressen of de live locatie van kinderen." },
    { id: "hulp", question: "Hoe bereiken we de organisatie via Messenger?", answer: "Open Hulp van de organisatie in je persoonlijke omgeving of Poortkamer. Je kunt daar een privébericht sturen over bijvoorbeeld jullie starttijd, samenloop of een vraag onderweg. Het gesprek blijft beschikbaar, zodat je later verder kunt praten. Een antwoord kan even duren. Voor een algemene vraag zonder account gebruik je de contactpagina. Bij direct gevaar bel je 112." },
    { id: "steunen", question: "Hoe kan ik de avond helpen of steunen?", answer: "Met een versierde poort, hulp bij een poortteam, materiaal, vakkennis of een financiële bijdrage. Ook buurtbedrijven zijn welkom. Laat via de sponsorpagina weten wat je wilt bijdragen, of meld je eigen plek aan. De organisatie neemt contact met je op om de mogelijkheden af te stemmen." },
  ]},
];
export const featuredFaq = faqCategories.flatMap(category => category.questions).filter(question => question.featured);
